version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - db
    environment:
      DATABASE_CONNECTION: 'postgres://postgres:example@db/meli-challenge'

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: meli-challenge
    ports:
      - "8889:5432"
